#================================================
# إعدادات البناء والنشر لمنصة Netlify
#================================================

# القسم الأول: إعدادات البناء
[build]
  # 1. pnpm install: لتثبيت الحزم (React, axios, etc.).
  # 2. pnpm run build: لبناء المشروع باستخدام Vite.
  command = "pnpm install && pnpm run build"

  # المجلد الذي يحتوي على الملفات النهائية بعد البناء (Vite يستخدم "dist").
  publish = "dist"


#================================================
# إعدادات إعادة التوجيه (Proxy) للواجهة الخلفية
#================================================

# القسم الثاني: إعادة توجيه طلبات الـ API
[[redirects]]
  # أي طلب يبدأ بـ /api/
  from = "/api/*"

  # سيتم تحويله إلى هذا الرابط في الواجهة الخلفية.
  to = "https://radwan2632.pythonanywhere.com/api/:splat"

  # كود الحالة 200 يعني أن التحويل "شفاف" (كأنه وكيل/proxy).
  status = 200
